### ISSUE TITLE
Where is the warm_up_train_file?

### ISSUE THREAD

**Issue by zealscott** [danyang-liu/AnchorKG#2]
Hi danyang,

Thanks for your excellent work! I try to reproduce the results, but I found that the warm_up_train_file does not exist and cannot be build from the scripts. So I am wondering if you could show me how to generate the warm_up_train_file for accelerate the training?

Thanks!

Yuntao

**Comment by Leavingseason** [comment]
This issue should have been addressed with @Micheallei 's recent PR: https://github.com/danyang-liu/AnchorKG/pull/3
